In [ ]:
import pandas as pd

In [1]:
from google.colab import files
uploaded=files.upload()

Saving temfile.csv to temfile.csv

In [5]:
df=pd.read_csv("temfile.csv")
df.head()

       City country_id      Country Latitude Longitude
0  Auckland        NEW  New Zealand   36.17S   175.03E
1  Auckland        NEW  New Zealand   36.17S   175.03E
2  Auckland        NEW  New Zealand   36.17S   175.03E
3  Auckland        NEW  New Zealand   36.17S   175.03E
4  Auckland        NEW  New Zealand   36.17S   175.03E

In [6]:
df.tail()

          City country_id Country Latitude Longitude
48465  Wroclaw        POL  Poland   50.63N    16.48E
48466  Wroclaw        POL  Poland   50.63N    16.48E
48467  Wroclaw        POL  Poland   50.63N    16.48E
48468  Wroclaw        POL  Poland   50.63N    16.48E
48469  Wroclaw        POL  Poland   50.63N    16.48E

In [7]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
df['citycat'] = labelencoder.fit_transform(df['City'].astype(str))
df.head(2000)

          City country_id      Country Latitude Longitude  citycat
0     Auckland        NEW  New Zealand   36.17S   175.03E        0
1     Auckland        NEW  New Zealand   36.17S   175.03E        0
2     Auckland        NEW  New Zealand   36.17S   175.03E        0
3     Auckland        NEW  New Zealand   36.17S   175.03E        0
4     Auckland        NEW  New Zealand   36.17S   175.03E        0
...        ...        ...          ...      ...       ...      ...
1995  Brasília        BRA       Brazil   15.27S    47.50W        1
1996  Brasília        BRA       Brazil   15.27S    47.50W        1
1997  Brasília        BRA       Brazil   15.27S    47.50W        1
1998  Brasília        BRA       Brazil   15.27S    47.50W        1
1999  Brasília        BRA       Brazil   15.27S    47.50W        1

[2000 rows x 6 columns]

In [8]:
df.tail()

          City country_id Country Latitude Longitude  citycat
48465  Wroclaw        POL  Poland   50.63N    16.48E       17
48466  Wroclaw        POL  Poland   50.63N    16.48E       17
48467  Wroclaw        POL  Poland   50.63N    16.48E       17
48468  Wroclaw        POL  Poland   50.63N    16.48E       17
48469  Wroclaw        POL  Poland   50.63N    16.48E       17

In [10]:
###One Hot Encoding
df1 = pd.read_csv("temfile.csv")
df1.head()

       City country_id      Country Latitude Longitude
0  Auckland        NEW  New Zealand   36.17S   175.03E
1  Auckland        NEW  New Zealand   36.17S   175.03E
2  Auckland        NEW  New Zealand   36.17S   175.03E
3  Auckland        NEW  New Zealand   36.17S   175.03E
4  Auckland        NEW  New Zealand   36.17S   175.03E

In [11]:
from sklearn.preprocessing import OneHotEncoder
oneHot = OneHotEncoder()
df1= df1.dropna()
result = oneHot.fit_transform(df1[['City']])
print(result)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (47961, 17)	1.0
  (47962, 17)	1.0
  (47963, 17)	1.0
  (47964, 17)	1.0
  (47965, 17)	1.0
  (47966, 17)	1.0
  (47967, 17)	1.0
  (47968, 17)	1.0
  (47969, 17)	1.0
  (47970, 17)	1.0
  (47971, 17)	1.0
  (47972, 17)	1.0
  (47973, 17)	1.0
  (47974, 17)	1.0
  (47975, 17)	1.0
  (47976, 17)	1.0
  (47977, 17)	1.0
  (47978, 17)	1.0
  (47979, 17)	1.0
  (47980, 17)	1.0
  (47981, 17)	1.0
  (47982, 17)	1.0
  (47983, 17)	1.0
  (47984, 17)	1.0
  (47985, 17)	1.0

In [12]:
newdf = df1.join(pd.DataFrame(result.toarray(),columns= oneHot.categories_))
newdf.head(200)

         City country_id      Country  ... (Uppsala,) (Warsaw,)  (Wroclaw,)
0    Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
1    Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
2    Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
3    Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
4    Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
..        ...        ...          ...  ...        ...       ...         ...
199  Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
200  Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
201  Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
202  Auckland        NEW  New Zealand  ...        0.0       0.0         0.0
203  Auckland        NEW  New Zealand  ...        0.0       0.0         0.0

[200 rows x 23 columns]

In [ ]:
dataset = [['milk','eggs','bread'],
          ['milk','bread'],
          ['eggs','sugar'],
          ['onion','coffee','carrot','icecream']]

In [13]:
pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.14.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (54.1.2)
Requirement already satisfied: matplotlib>=1.5.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: pandas>=0.17.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.5)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->mlxtend) (1.0.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=1.5.1->mlxtend) (0.10.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.17.1->mlxtend) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=1.5.1->mlxtend) (1.15.0)

In [17]:
from mlxtend.preprocessing import TransactionEncoder
encoder = TransactionEncoder().fit("teamfile.csv")
oneHot = encoder.transform("teamfile.csv")
oneHot = pd.DataFrame(oneHot,columns= encoder.columns_)
print(oneHot)

        .      a      c      e      f      i      l      m      s      t      v
0   False  False  False  False  False  False  False  False  False   True  False
1   False  False  False   True  False  False  False  False  False  False  False
2   False   True  False  False  False  False  False  False  False  False  False
3   False  False  False  False  False  False  False   True  False  False  False
4   False  False  False  False   True  False  False  False  False  False  False
5   False  False  False  False  False   True  False  False  False  False  False
6   False  False  False  False  False  False   True  False  False  False  False
7   False  False  False   True  False  False  False  False  False  False  False
8    True  False  False  False  False  False  False  False  False  False  False
9   False  False   True  False  False  False  False  False  False  False  False
10  False  False  False  False  False  False  False  False   True  False  False
11  False  False  False  False  False  False  False  False  False  False   True

In [18]:
## Jaccard Similarity
import scipy.spatial
jaccard = scipy.spatial.distance.cdist(oneHot,oneHot,metric= 'jaccard')
jaccarddis = pd.DataFrame(jaccard,columns=oneHot.index.values,index=oneHot.index.values)
print(jaccard)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]

In [19]:
print(jaccarddis)

     0    1    2    3    4    5    6    7    8    9    10   11
0   0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
1   1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
2   1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
3   1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
4   1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
5   1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0
6   1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0
7   1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0
8   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0
9   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0
10  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0
11  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0

In [20]:
print("Less distance means they are more similar. 1 is closed to 0,2 is closed to 3")

Less distance means they are more similar. 1 is closed to 0,2 is closed to 3

In [21]:
from scipy.spatial import distance 
mink_dist0 = distance.minkowski(jaccarddis[0],3) 
mink_dist1 = distance.minkowski(jaccarddis[1],3)
mink_dist2 = distance.minkowski(jaccarddis[2],3)
mink_dist3= distance.minkowski(jaccarddis[3],3)
print(mink_dist0)
print(mink_dist1)
print(mink_dist2)
print(mink_dist3)

7.280109889280518
7.615773105863909
7.280109889280518
7.280109889280518

In [22]:
print("0 is closer to everyone compred to others")

0 is closer to everyone compred to others